apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: tableflip
  labels:
    knative.dev/type: "function"
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: github.com/n3wscott/tableflip/cmd/flip/
